#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""Generate both README hero images from the SVG assets."""

import math
from copy import deepcopy
from pathlib import Path
from xml.etree import ElementTree as ET

ASSETS = Path(__file__).resolve().parents[1] / "Assets"
SVG = "http://www.w3.org/2000/svg"
ET.register_namespace("", SVG)

# Arrange icons by hue, from red through green and blue to purple.
# Each entry pairs an asset name with its dark appearance background color.
SERVICES = (
    ("calendar", "#ff453a"),
    ("contacts", "#ac8e68"),
    ("reminders", "#ff9f0a"),
    ("messages", "#28d74b"),
    ("phone", "#28d74b"),
    ("weather", "#5ac8f5"),
    ("location", "#0a84ff"),
    ("shortcuts", "#5e5ce6"),
    ("maps", "#bf5af2"),
)

WIDTH, HEIGHT = 1012, 600
ICON_SIZE = 100
RADIUS = 600
ARC_TOP = 108
SWEEP = math.radians(90)


def icon_centers(count: int) -> list[tuple[float, float]]:
    """Space centers equally along a circular arc, from left to right."""
    centers = []
    for index in range(count):
        angle = -SWEEP / 2 + SWEEP * index / (count - 1) if count > 1 else 0
        # Arc length is radius * angle, so equal angles give equal spacing.
        x = WIDTH / 2 + RADIUS * math.sin(angle)
        y = ARC_TOP + RADIUS * (1 - math.cos(angle))
        centers.append((x, y))
    return centers


def generate(theme: str) -> None:
    root = ET.Element(f"{{{SVG}}}svg", {"viewBox": f"0 0 {WIDTH} {HEIGHT}"})
    root.append(ET.Comment(" Generated by Scripts/generate-hero.py. Do not edit. "))
    ET.SubElement(root, f"{{{SVG}}}title").text = "iMCP"

    wordmark = ET.parse(ASSETS / "wordmark.svg").getroot()
    lettering = deepcopy(wordmark.find(f"{{{SVG}}}g"))
    lettering.set("fill", "#fff" if theme == "dark" else "#000")
    root.append(lettering)

    for (name, dark_color), (x, y) in zip(SERVICES, icon_centers(len(SERVICES))):
        icon = ET.parse(ASSETS / f"{name}.svg").getroot()
        icon.set("x", f"{x - ICON_SIZE / 2:.3f}")
        icon.set("y", f"{y - ICON_SIZE / 2:.3f}")
        icon.set("width", str(ICON_SIZE))
        icon.set("height", str(ICON_SIZE))
        ET.SubElement(icon, f"{{{SVG}}}title").text = name.capitalize()
        if theme == "dark":
            icon.find(f"{{{SVG}}}circle").set("fill", dark_color)
        root.append(icon)

    ET.indent(root, space="  ")
    output = ET.tostring(root, encoding="unicode")
    (ASSETS / f"hero-{theme}.svg").write_text(
        '<?xml version="1.0" encoding="UTF-8"?>\n' + output + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    for theme in ("light", "dark"):
        generate(theme)
